port: 7880
bind_addresses:
  - ""
rtc:
  tcp_port: 7881
  port_range_start: 50000
  port_range_end: 60000
  use_external_ip: true

keys:
  #colocar as chaves também no .env da API
  API_KEY_EXEMPLO: "SECRET_KEY_EXEMPLO"


webhook:
  urls:
    - "http://api:3000/webhooks/livekit"